rh_homepage:
    path:     /
    defaults: { _controller: RHBundle:Default:index }

listcandidats:
    path: /list_cand
    defaults: { _controller:  RHBundle:Default:listCandidats  }

showformentretient:
    path: /affecter/{cin}
    defaults: { _controller:  RHBundle:Default:affecterForm }

affecterentredb:
    path: /affectertoDb/{cin}
    defaults: { _controller:  RHBundle:Default:affecterDB }

listentretients:
    path: /listEntre
    defaults:  { _controller:  RHBundle:Default:showEntretiens}

